server:
  port: 8083
  servlet:
    context-path: /auth-service

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:${LIBRARY_DB_PORT:3306}/library_auth_db?createDatabaseIfNotExist=true
    username: ${LIBRARY_DB_USERNAME:root}
    password: ${LIBRARY_DB_PASSWORD:1qazxsw2}
#    password: 1qazxsw2

  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
