server:
  port: 8083
  servlet:
    context-path: /auth-service

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/library_auth_db?createDatabaseIfNotExist=true
    username: root
    password: 1qazxsw2

  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration