server:
  port: 8082
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/library_user_db?createDatabaseIfNotExist=true
    username: root
    password: 1qazxsw2

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true