server:
  port: 8082
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:${LIBRARY_DB_PORT:3306}/library_user_db?createDatabaseIfNotExist=true
    username: ${LIBRARY_DB_USERNAME:root}
    password: ${LIBRARY_DB_PASSWORD:1qazxsw2}

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
